name: tests

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          echo "testing: ${{github.ref}}"
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements_dev.txt
      - name: Lint
        run: |
          black . --check
          isort . --check
          flake8
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Preprocess test
        run: |
          pytest
      - name: Test
        run: |
          pytest --cov
      - name: Coveralls
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            pip install coveralls
            coveralls --service=github
